# The URL the site will be built for
base_url = "https://zuiyu1998.github.io/"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

theme = "even"


taxonomies = [
    { name = "categories", feed = true },
    { name = "tags", feed = true },
]

[markdown]
# When set to "true", emoji aliases translated to their corresponding
# Unicode emoji equivalent in the rendered Markdown files. (e.g.: :smile: => 😄)
render_emoji = false

# Whether external links are to be opened in a new tab
# If this is true, a `rel="noopener"` will always automatically be added for security reasons
external_links_target_blank = false

# Whether to set rel="nofollow" for all external links
external_links_no_follow = false

# Whether to set rel="noreferrer" for all external links
external_links_no_referrer = false

# Whether to set rel="external" for all external links
external_links_external = true

# Whether smart punctuation is enabled (changing quotes, dashes, dots in their typographic form)
# For example, `...` into `…`, `"quote"` into `“curly”` etc
smart_punctuation = false

# Whether parsing of definition lists is enabled
definition_list = false

# Whether to set decoding="async" and loading="lazy" for all images
# When turned on, the alt text must be plain text.
# For example, `![xx](...)` is ok but `![*x*x](...)` isn’t ok
lazy_async_image = false

# Whether footnotes are rendered in the GitHub-style (at the bottom, with back references) or plain (in the place, where they are defined)
bottom_footnotes = false

# When set to "true", support for GitHub-style alerts, a.k.a. callouts or admonitions, is enabled in the Markdown parser.
# For example, this Markdown syntax:
#
#     > [!NOTE]
#     > alert note
#
# will result in the following generated HTML:
#
#     <blockquote class="markdown-alert-note">
#     <p>alert note</p>
#     </blockquote>
#
# where the CSS class name suffix may be `note`, `tip`, `important`, `warning`, or `caution`, depending on the alert type.
# Visual appearance depends on theme-level support; refer to your theme's documentation for more information.
github_alerts = false

# This determines whether to insert a link for each header like the ones you can see on this site if you hover over
# a header.
# The default template can be overridden by creating an `anchor-link.html` file in the `templates` directory.
# This value can be "left", "right", "heading" or "none".
# "heading" means the full heading becomes the text of the anchor.
# See "Internal links & deep linking" in the documentation for more information.
insert_anchor_links = "none"

# Syntax highlighting configuration (optional)
[markdown.highlighting]
# When set to "true", missing highlight languages are treated as errors. Defaults to false but recommended to set to true.
error_on_missing_language = false

# Whether to use inline hex colours (`inline`) or CSS classes (`class`) 
style = "inline"

# Selecting a theme is always required: you have a choice between single (1) or dual themes (2).
# Only outputting CSS classes like before 0.22 is not possible anymore.
# 1. If you use a single theme, put its name here. See the syntax highlighting page for the possible choices.
theme = ""

# 2. If you want light/dark themes, use the 2 fields below instead. See the syntax highlighting page for the possible choices.
light_theme = ""
dark_theme = ""

# A list of files for additional JSON TextMate grammars
extra_grammars = []

# A list of files for additional JSON TextMate themes
# Get themes from https://textmate-grammars-themes.netlify.app/
extra_themes = []


[extra]
# Put all your custom variables here

even_title = "zuiyu's blog"

even_menu = [
    {url = "$BASE_URL", name = "首页"},
    # {url = "$BASE_URL/categories", name = "Categories"},
    {url = "$BASE_URL/tags", name = "标签"},
    # {url = "$BASE_URL/about", name = "About"},
]